### ISSUE TITLE
UnboundLocalError: local variable 'flagsIndGT' referenced before assignment

### ISSUE THREAD

**Issue by KennethEnevoldsen** [MikeMpapa/CNNs-Speech-Music-Discrimination#6]
Dear Mike,

A group I am working with is intending to hopefully utilize this project in an upcoming publication. (assuming it generalise well to Danish)
I have read previous issues and found [xtluo-ai](/xtluo-ai) comments especially useful. 

However I am currently running in to the problem stated in the title:
"UnboundLocalError: local variable 'flagsIndGT' referenced before assignment"

Looking at "ClassifyWav.py", however I found the issue to be the missing '*_true.mat' file, which is seemingly a ground truth file. I however have no intention of using a ground truth, besides the initial performance testing. 

Is it possible to utilize the already pretrained model, without such a file? Couldn't find any method in the readme nor in the code itself. I might however have missed something.

Thanks in advance,
Kenneth Enevoldsen
__
If relevant the script is currently run in using the caffe docker optimized for CPU:
https://hub.docker.com/r/bvlc/caffe/

**Comment by MikeMpapa** [comment]
Hi Keneth,

The mat files are needed only to repeat the experiments provided in the
paper. They contain the true labels for the 11h dataset (D1) used for
evaluation which unfortunately I cannot share due to copyrights. D2 and D3
though are free online and you can test the system there.

However if you wish to use the pretrained models for your own framework the
only think you need to do is to load the model and evaluate it in your own
dataset assuming that you know the ground truth labels. You will have to
build your own code for that though using as a guideline the ClassifyWav.py


Thanks,
*Michalis Papakostas*

PhD Candidate
Heracleia - Human Centered Computing Lab
Department of Computer Science
University of Texas, Arlington


Στις Πέμ, 28 Φεβ 2019 στις 12:49 μ.μ., ο/η KennethEnevoldsen <
notifications@github.com> έγραψε:

**Comment by KennethEnevoldsen** [comment]
Hei Mike, 

Thanks for the quick reply. Sounds reasonable.
